---
  - name: Make sure nginx isn't running
    service: name=nginx state=stopped

  - name: Start supervisor process
    supervisorctl: name=charlestonjsserver state=started config=/etc/supervisor/supervisor.conf
