---
  - name: Install application dependencies
    npm: path=/var/www/html/charlestonjs

  - name: Install charlestonjs supervisor config
    copy: src=supervisor_charlestonjs.conf dest=/etc/supervisor/conf.d/supervisor_charlestonjs.conf

  - name: Install nginx supervisor config
    copy: src=supervisor_nginx.conf dest=/etc/supervisor/conf.d/supervisor_nginx.conf

  - name: Install nginx config
    copy: src=nginx.conf dest=/etc/nginx/nginx.conf

  - name: Install site config
    copy: src=charlestonjs dest=/etc/nginx/sites-available/charlestonjs

  - name: Enable site
    shell: ln -s /etc/nginx/sites-available/charlestonjs /etc/nginx/sites-enabled
    ignore_errors: yes

  - name: Disable default site
    shell: unlink /etc/nginx/sites-enabled/default
    ignore_errors: yes
