---
  - name: Install application dependencies
    npm: path=/var/www/html/charlestonjs

  - name: Install supervisor config
    copy: src=supervisor.conf dest=/etc/supervisor/conf.d/supervisor.conf
    ignore_errors: yes

  - name: Install nginx config
    copy: src=nginx.conf dest=/etc/nginx/nginx.conf

  - name: Install site config
    copy: src=charlestonjs dest=/etc/nginx/sites-available/charlestonjs

  - name: Enable site
    shell: ln -s /etc/nginx/sites-available/charlestonjs /etc/nginx/sites-enabled
    ignore_errors: yes

  - name: Disabled default site
    shell: rm /etc/nginx/sites-enabled/default
    ignore_errors: yes

  - name: Remove default index html file
    shell: rm /var/wwww/html/index.nginx-debian.html
    ignore_errors: yes
